apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-bazel
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
        - .
    # bazel:
    #   target: //:skaffold_example.tar
