apiVersion: skaffold/v2beta3
kind: Config
build:
  artifacts:
    - image: skaffold-example
      kaniko:
        cache: {}
  cluster:
    pullSecretName: e2esecret-with-path
    pullSecret:     kaniko-secret.json
    namespace: default
deploy:
  kubectl:
    manifests:
      - k8s-*
